Adding Script to run SwiftFormat and SwiftLint and custom rules config files
ios-course/simple-network-service pull request #16
Opened 2023-08-31 10:14 UTC by iBYarchitect

### Summary
This PR resolve #8.

### Changes
- .swiftformat
- .swift-version
- .swiftlint.yml
- 

### Checks to complete

- [x] The PR title has a conventional commit style (short and descriptive).
- [x] The PR description includes essential information that helps understand the purpose of the changes.
- [x] I've built and run my changes, and no warnings or errors occurred.
- [x] All existing tests passed with my changes.
- [x] My code follows our style guide.
- [x] I've performed a self-review of my code.
- [x] Every non-private interface is documented properly.
- [x] I've added tests for my code (if it makes sense).
- [x] I've updated `CHANGELOG.md` file.
- [x] PR has assignee, reviewers, milestone, it is properly linked to the project and to the issue.

2023-09-01 09:53 UTC, kirpichonok requested changes
Almost done, but there are several violations left in the `HTTPAPIEndpoint` and `NetworkService` files.  Please, correct them to bring the project into compliance with our rules completely.
I'm not sure that we really need this script. It's not difficult to run swiftlint and swiftformat commands manually and not to add 23 lines of code. That is more robust, I think.
<img width="1192" alt="Screenshot 2023-09-01 at 12 52 38" src="https://github.com/ios-course/simple-network-service/assets/110284165/05bc9a66-e625-4260-8912-917baa75392d">

2023-09-04 05:35 UTC, kirpichonok commented on .RunSwiftFormatSwiftLint.sh
Will be great, if you remove the script.

2023-09-04 09:31 UTC, iBYarchitect commented on .RunSwiftFormatSwiftLint.sh
Deleted with 9b39b8a

2023-09-04 09:46 UTC, kirpichonok approved these changes
LGTM

2023-09-04 09:52 UTC, NadzeyaShpakouskaya approved these changes
LGTM to unblock

2023-09-04 10:05 UTC, merged